ARG GO_VERSION=1.15

FROM golang:${GO_VERSION}-alpine As builder

ENV PORT=3002

RUN apk update && apk add alpine-sdk git && rm -rf /var/cache/apk/*

RUN mkdir -p /api

WORKDIR /api

COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

RUN go get github.com/swaggo/swag/cmd/swag
RUN swag init -g src/main.go

CMD ["go", "test", "-v", "-cover", "./..."]
