package main

import (
	"github.com/vipin030/automan/controllers"
	"github.com/vipin030/automan/models"
	"os"
	"net/http"
	"fmt"
	"strings"
	jwt "github.com/dgrijalva/jwt-go"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"

	"github.com/vipin030/automan/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server celler server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:3001
// @BasePath /api/v1
// @query.collection.format multi


func main() {
	r := gin.Default()

	// Connect to database
	models.ConnectDatabase()

	docs.SwaggerInfo.Title = "Automan REST API"
	docs.SwaggerInfo.Description = "This is a sample localhost server."
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = "localhost:3001"
	docs.SwaggerInfo.BasePath = "/api/v1"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	// Routes
	r.POST("/login", controllers.Authenticate)

	v1 := r.Group("/api/v1")
	{
		vtypes := v1.Group("/vtypes")
		{
			vtypes.GET("", TokenAuthMiddleware(),controllers.FindVehicleTypes)
			vtypes.GET(":id", controllers.FindVehicleType)
			vtypes.POST("", controllers.CreateVehicleType)
			vtypes.PATCH(":id", controllers.UpdateVehicleType)
			vtypes.DELETE(":id", controllers.DeleteVehicleType)
		}
	}
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Run the server
	r.Run(":8080")
}

func ExtractToken(r *http.Request) string {
  bearToken := r.Header.Get("Authorization")
  //normally Authorization the_token_xxx
  strArr := strings.Split(bearToken, " ")
  if len(strArr) == 2 {
     return strArr[1]
  }
  return ""
}

func VerifyToken(r *http.Request) (*jwt.Token, error) {
  tokenString := ExtractToken(r)
  token, err := jwt.Parse(tokenString, func(token *jwt.Token) (interface{}, error) {
     //Make sure that the token method conform to "SigningMethodHMAC"
     if _, ok := token.Method.(*jwt.SigningMethodHMAC); !ok {
        return nil, fmt.Errorf("unexpected signing method: %v", token.Header["alg"])
     }
     return []byte(os.Getenv("ACCESS_SECRET")), nil
  })
  if err != nil {
     return nil, err
  }
  return token, nil
}

func TokenValid(r *http.Request) error {
  token, err := VerifyToken(r)
  if err != nil {
     return err
  }
  if _, ok := token.Claims.(jwt.Claims); !ok && !token.Valid {
     return err
  }
  return nil
}

func TokenAuthMiddleware() gin.HandlerFunc {
  return func(c *gin.Context) {
     err := TokenValid(c.Request)
     if err != nil {
				c.JSON(http.StatusUnauthorized, gin.H{"error": err.Error()})
        c.Abort()
        return
     }
     c.Next()
  }
}
