package main

import (
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"

	"github.com/vipin030/automan/docs" // docs is generated by Swag CLI, you have to import it.
	"github.com/vipin030/automan/src/controllers"
	"github.com/vipin030/automan/src/middleware"
	"github.com/vipin030/automan/src/utils/logger"
)

// @title Swagger Example API
// @version 1.0
// @description This is a sample server celler server.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:3001
// @BasePath /api/v1
// @query.collection.format multi

func main() {
	r := gin.Default()

	//   - Logs all requests, like a combined access and error log.
	//   - Logs to stdout.
	//   - RFC3339 with UTC time format.
	r.Use(logger.AccessLog())

	// Logs all panic to error log
	//   - stack means whether output the stack info.
	r.Use(logger.PanicLog())

	logger.Info("About to start the application")
	docs.SwaggerInfo.Title = "Automan REST API"
	docs.SwaggerInfo.Description = "This is a sample localhost server."
	docs.SwaggerInfo.Version = "1.0"
	docs.SwaggerInfo.Host = "localhost:3001"
	docs.SwaggerInfo.BasePath = "/api/v1"
	docs.SwaggerInfo.Schemes = []string{"http", "https"}

	// Routes
	r.POST("/login", controllers.Authenticate)
	r.POST("/signup", controllers.CreateUserAccount)

	r.Use(middleware.TokenAuthMiddleware())
	v1 := r.Group("/api/v1")
	{
		vtypes := v1.Group("/vtypes")
		{
			vtypes.GET("", controllers.FindVehicleTypes)
			vtypes.GET(":id", controllers.FindVehicleType)
			vtypes.POST("", controllers.CreateVehicleType)
			vtypes.PATCH(":id", controllers.UpdateVehicleType)
			vtypes.DELETE(":id", controllers.DeleteVehicleType)
		}
	}
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Run the server
	r.Run(":8080")
}
